services:
  server:
    build:
      context: .
    depends_on:
      - db
    links:
      - db
    environment:
      NODE_ENV: production
      DB_HOST: db
    ports:
      - 3000:3000

  db:
    image: mysql:latest
    restart: always
    volumes:
      - ./cmsUsers-mysql.sql:/docker-entrypoint-initdb.d/1.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: zse_tai3
    ports:
      - 3306:3306